version: '3.9'

services:
  database:
    image: postgres:13.4-alpine
    container_name: database-api
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - pgdata:/data/postgres

  api:
    build: .
    container_name: api
    ports:
      - 3333:3333
    volumes:
      - .:/usr/api
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
